export const IS_TABLET_ABOVE_INCH = 6.5;
export const IS_WEAR_UNDER_SIZE = 1000; // width + height

export enum PlatformGroup {
    smarttv = 'smarttv',
    electron = 'electron',
}

export enum FormFactor {
    generic = 'generic',
    mobile = 'mobile',
    desktop = 'desktop',
    watch = 'watch',
    tv = 'tv',
    browser = 'browser',
}

export enum Engine {
    generic = 'generic',
    lightning = 'engine-lightning',
    rn_electron = 'engine-rn-electron',
    rn_macos = 'engine-rn-macos',
    rn_next = 'engine-rn-next',
    rn_tvos = 'engine-rn-tvos',
    rn_web = 'engine-rn-web',
    rn_windows = 'rengine-rn-windows',
    rn = 'engine-rn',
}

export enum Platform {
    generic = 'generic',
    ios = 'ios',
    tvos = 'tvos',
    appleauto = 'appleauto',
    android = 'android',
    androidtv = 'androidtv',
    androidwear = 'androidwear',
    androidauto = 'androidauto',
    alexa = 'alexa',
    firefoxos = 'firefoxos',
    firefoxtv = 'firefoxtv',
    firetv = 'firetv',
    fireos = 'fireos',
    kaios = 'kaios',
    linux = 'linux',
    macos = 'macos',
    tizen = 'tizen',
    tizenmobile = 'tizenmobile',
    tizenwatch = 'tizenwatch',
    web = 'web',
    webos = 'webos',
    webtv = 'webtv',
    windows = 'windows',
    xbox = 'xbox',
    astian = 'astian',
    blackberry = 'blackberry',
    chromecast = 'chromecast',
    chromeos = 'chromeos',
    hbbtv = 'hbbtv',
    meego = 'meego',
    netcast = 'netcast',
    occulus = 'occulus',
    orsay = 'orsay',
    ps4 = 'ps4',
    roku = 'roku',
    sailfish = 'sailfish',
    tivo = 'tivo',
    ubuntu = 'ubuntu',
    ubuntutouch = 'ubuntutouch',
    unity = 'unity',
    vewd = 'vewd',
    vidaa = 'vidaa',
    vieraconnect = 'vieraconnect',
    vizio = 'vizio',
    watchos = 'watchos',
    webian = 'webian',
    wii = 'wii',
    wp10 = 'wp10',
    wp8 = 'wp8',
}
