
use_frameworks!

target 'RNVAppTVOS' do
  platform :tvos, '10.0'
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  'DevSupport',
  'CxxBridge',
  'RCTAnimation',
  'RCTLinkingIOS',
  'RCTSettings'
  ]

  pod "yoga", :path => "../../node_modules/react-native/ReactCommon/yoga"
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
{{PLUGIN_PATHS}}
end
