// This file is generated by ReNative.
// To override it simply copy/create ./appConfigs/base/builds/windows/contextMenu.js file

const { Menu } = require('electron');

let createWindow;

const template = [
    // { role: 'appMenu' }
    ...[],
    // { role: 'fileMenu' }
    {
        label: 'File',
        submenu: [
            isMac ? { role: 'close' } : { role: 'quit' }
        ]
    },
    // { role: 'editMenu' }
    {
        label: 'Edit',
        submenu: [
            { role: 'undo' },
            { role: 'redo' },
            { type: 'separator' },
            { role: 'cut' },
            { role: 'copy' },
            { role: 'paste' },
            ...[
                { role: 'delete' },
                { type: 'separator' },
                { role: 'selectAll' }
            ]
        ]
    },
    // { role: 'viewMenu' }
    {
        label: 'View',
        submenu: [
            { role: 'reload' },
            { role: 'forcereload' },
            { role: 'toggledevtools' },
            { type: 'separator' },
            { role: 'resetzoom' },
            { role: 'zoomin' },
            { role: 'zoomout' },
            { type: 'separator' },
            { role: 'togglefullscreen' }
        ]
    },
    // { role: 'windowMenu' }
    {
        label: 'Window',
        submenu: [
            { role: 'minimize' },
            { role: 'zoom' },
            ...[
                { role: 'close' }
            ]
        ]
    },
    {
        role: 'help',
        submenu: [
            {
                label: 'Learn More',
                click: async () => {
                    const { shell } = require('electron');
                    await shell.openExternal('https://renative.org');
                }
            }
        ]
    }
];

exports.initContextMenu = function (createWindowHandler) {
    createWindow = createWindowHandler;
    const menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
};
