export const RnvFileName = {
    renative: 'renative.json',
    renativeLocal: 'renative.local.json',
    renativePrivate: 'renative.private.json',
    renativeTemplate: 'renative.template.json',
    renativeBuild: 'renative.build.json',
    renativeRuntime: 'renative.runtime.json',
    renativeWorkspaces: 'renative.workspaces.json',
    renativeTemplates: 'renative.templates.json',
    renativePlatforms: 'renative.platforms.json',
    renativeEngine: 'renative.engine.json',
    package: 'package.json',
    rnvJson: 'rnv.json',
    // renativeProject: 'renative.project.json',
} as const;
