export const RnvTaskName = {
    run: 'run',
    configure: 'configure',
    doctor: 'doctor',
    new: 'new',
    help: 'help',
    build: 'build',
    info: 'info',
    start: 'start',
    export: 'export',
    debug: 'debug',
    package: 'package',
    deploy: 'deploy',
    log: 'log',
    clean: 'clean',
    link: 'link',
    unlink: 'unlink',
    publish: 'publish',
    switch: 'switch',
    targetLaunch: 'target launch',
    targetList: 'target list',
    target: 'target',
    templateAdd: 'template add',
    templateList: 'template list',
    templateApply: 'template apply',
    workspaceAdd: 'workspace add',
    workspaceConnect: 'workspace connect',
    workspaceList: 'workspace list',
    workspaceUpdate: 'workspace update',
    platformConfigure: 'platform configure',
    platformConnect: 'platform connect',
    platformEject: 'platform eject',
    platformList: 'platform list',
    projectPlatforms: 'project platforms',
    sdkConfigure: 'sdk configure',
    projectConfigure: 'project configure',
    projectUpgrade: 'project upgrade',
    pluginAdd: 'plugin add',
    pluginList: 'plugin list',
    pluginUpdate: 'plugin update',
    cryptoEncrypt: 'crypto encrypt',
    cryptoDecrypt: 'crypto decrypt',
    cryptoInstallCerts: 'crypto installCerts',
    cryptoInstallProfiles: 'crypto installProfiles',
    cryptoInstallProfile: 'crypto installProfile',
    cryptoUpdateProfile: 'crypto updateProfile',
    cryptoUpdateProfiles: 'crypto updateProfiles',
    hooksRun: 'hooks run',
    hooksList: 'hooks list',
    hooksPipes: 'hooks pipes',
    pkg: 'pkg',
    appConfigure: 'app configure',
    appCreate: 'app create',
    appSwitch: 'app switch',
    workspaceConfigure: 'workspace configure',
    configureSoft: 'configureSoft',
    kill: 'kill',
    eject: 'eject',
    telemetryDisable: 'telemetry disable',
    telemetryEnable: 'telemetry enable',
    telemetryStatus: 'telemetry status',
    config: 'config',
    patchReset: 'patch reset',
} as const;
