// TO DO This needs to be generated by SDK and injected. Not defined here

module.exports = {
  project: {
    windows: {
      sourceDir: 'platformBuilds/projectName_windows',
      solutionFile: 'projectName.sln',
      project: {
        projectFile: 'projectName\\projectName.vcxproj',
      },
    },
  },
};