import { AnyZodObject, z } from 'zod';
import { RnvCommonSchema, zodCommonSchema } from '../common';
import { Ext, ExtendTemplate, PlatformsKeys, Runtime, SupportedPlatforms, TemplateConfig } from '../shared';
import { RnvPlatformsSchema, zodPlatformsSchema as zodPlatformsSchema } from '../platforms';
import { RnvPluginsSchema, zodPluginsSchema } from '../plugins';

const DefaultCommandSchemes = z
    .record(z.enum(['run', 'export', 'build']), z.string())
    .describe(
        'List of default schemes for each rnv command. This is useful if you want to avoid specifying `-s ...` every time your run rnv command. bu default rnv uses `-s debug`. NOTE: you can only use schemes you defined in `buildSchemes`'
    );

const Targets = z.record(PlatformsKeys, z.string()).describe('Override of default targets specific to this project');

const Ports = z
    .record(PlatformsKeys, z.number()) //TODO maxValue(65535)
    .describe(
        'Allows you to assign custom port per each supported platform specific to this project. this is useful if you foten switch between multiple projects and do not want to experience constant port conflicts'
    );

const PortOffset = z.number().describe('Offset each port default value by increment');

const MonoRoot = z.string().describe('Define custom path to monorepo root where starting point is project directory');

const Env = z.record(z.string(), z.any()).describe('Object containing injected env variables');

export const DefaultsSchema = z
    .object({
        ports: z.optional(Ports),
        supportedPlatforms: z.optional(SupportedPlatforms),
        portOffset: z.optional(PortOffset),
        defaultCommandSchemes: z.optional(DefaultCommandSchemes),
        targets: z.optional(Targets),
    })
    .describe('Default system config for this project');

const Pipes = z
    .array(z.string())
    .describe(
        'To avoid rnv building `buildHooks/src` every time you can specify which specific pipes should trigger recompile of buildHooks'
    );

const WorkspaceID = z
    .string() //TODO: no spaces
    .describe(
        'Workspace ID your project belongs to. This will mach same folder name in the root of your user directory. ie `~/` on macOS'
    );

const Tasks = z
    .object({
        install: z.optional(
            z.object({
                script: z.string(),
                platform: z.optional(
                    z.record(
                        PlatformsKeys,
                        z.object({
                            ignore: z.optional(z.boolean()),
                            ignoreTasks: z.optional(z.array(z.string())),
                        })
                    )
                ),
            })
        ),
    })
    .describe(
        'Allows to override specific task within renative toolchain. (currently only `install` supported). this is useful if you want to change specific behaviour of built-in task. ie install task triggers yarn/npm install by default. but that might not be desirable installation trigger'
    );

const Integrations = z
    .record(z.string(), z.object({}))
    .describe('Object containing integration configurations where key represents package name');

const Engine = z.literal('source:rnv');

const IsMonoRepo = z.boolean().describe('Mark if your project is part of monorepo');

const Crypto = z
    .object({
        path: z
            .string()
            .describe('Relative path to encrypted file in your renative project. Example: "./secrets/mySecrets.enc"'),
        isOptional: z.boolean().optional().describe('Mark if crypto object should not checked every run'),
    })
    .describe(
        'This prop enables automatic encrypt and decrypt of sensitive information in your project. \nRNV will generate new env variable with can be used to encrypt and decrypt. this env var is generated by combining (and sanitizing) 2 properties from your renative.json: \nworkspaceID + projectName.\nThese 2 properties are also used to generate path on your local machine where encrypted files will be decrypted into.'
    );

const Permissions = z
    .object({
        android: z.optional(
            z
                .record(
                    z.string(),
                    z.object({
                        key: z.string(), //TODO: type this
                        security: z.string(), //TODO: type this
                    })
                )
                .describe('Android SDK specific permissions')
        ),
        ios: z.optional(
            z
                .record(
                    z.string(), //TODO: type this
                    z.object({
                        desc: z.string(),
                    })
                )
                .describe('iOS SDK specific permissions')
        ),
    })
    .describe(
        'Permission definititions which can be used by app configs via `includedPermissions` and `excludedPermissions` to customize permissions for each app'
    );

export const EnginesSchema = z.record(z.string(), Engine).describe('List of engines available in this project');

const EnableHookRebuild = z
    .boolean()
    .describe(
        'If set to true in `./renative.json` build hooks will be compiled at each rnv command run. If set to `false` (default) rebuild will be triggered only if `dist` folder is missing, `-r` has been passed or you run `rnv hooks run` directly making your rnv commands faster'
    );

const ProjectName = z
    .string()
    .describe(
        'Name of the project which will be used in workspace as folder name. this will also be used as part of the KEY in crypto env var generator'
    );

const Paths = z
    .object({
        appConfigsDir: z.optional(z.string().describe('Custom path to appConfigs. defaults to `./appConfigs`')),
        platformTemplatesDirs: z.optional(
            z
                .record(PlatformsKeys, z.string())
                .describe(
                    'Custom location of ejected platform templates. this is populated after you run `rnv platform eject`'
                )
        ),
        appConfigsDirs: z.optional(z.array(z.string()).describe('Array of custom location app configs directories`')),
        platformAssetsDir: z.optional(
            z.string().describe('Custom path to platformAssets folder. defaults to `./platformAssets`')
        ),
        platformBuildsDir: z.optional(
            z.string().describe('Custom path to platformBuilds folder. defaults to `./platformBuilds`')
        ),
        pluginTemplates: z.optional(
            z.record(
                z.string(),
                z.object({
                    npm: z.optional(z.string()),
                    path: z.string(),
                })
            ).describe(`
        Allows you to define custom plugin template scopes. default scope for all plugins is \`rnv\`.
        this custom scope can then be used by plugin via \`"source:myCustomScope"\` value
        
        those will allow you to use direct pointer to preconfigured plugin:
        
        \`\`\`
        "plugin-name": "source:myCustomScope"
        \`\`\`
        
        NOTE: by default every plugin you define with scope will also merge any
        files defined in overrides automatically to your project.
        To skip file overrides coming from source plugin you need to detach it from the scope:
        
        \`\`\`
        {
            "plugins": {
                "plugin-name": {
                    "source": ""
                }
            }
        }
        \`\`\`
        `)
        ),
    })
    .describe('Define custom paths for RNV to look into');

//LEVEl 0 (ROOT)

const zodRootProjectBaseFragment = z
    .object({
        workspaceID: WorkspaceID,
        projectVersion: z.string(), // TODO: if undefined it should infer from package.json
        projectName: ProjectName,

        isTemplate: z.boolean(),
        defaults: z.optional(DefaultsSchema),
        pipes: z.optional(Pipes),
        crypto: z.optional(Crypto),
        paths: z.optional(Paths),
        permissions: z.optional(Permissions),
        engines: z.optional(EnginesSchema), // TODO: rename to mods (mods with type engine in the future) ?
        enableHookRebuild: z.optional(EnableHookRebuild),
        extendsTemplate: z.optional(ExtendTemplate), // TODO: rename to "extendsConfig"
        tasks: z.optional(Tasks),
        integrations: z.optional(Integrations), // TODO: rename to mods
        env: z.optional(Env),
        runtime: z.optional(Runtime),
        templateConfig: z.optional(TemplateConfig),
        _meta: z.optional(
            z.object({
                requires_first_template_apply: z.optional(SupportedPlatforms),
            })
        ),
        // DEPRECATED

        isMonorepo: z.optional(IsMonoRepo), // TODO: remove and use auto detection
        monoRoot: z.optional(MonoRoot), // TODO: remove and use auto detection
        custom: z.optional(Ext), // TODO: find better way to handle
        skipAutoUpdate: z
            .boolean()

            .describe(
                "Enables the equivalent to passing --skipDependencyCheck parameter on every rnv run so you don't have to use it"
            ),
        // REMOVED
        // useTemplate: z.optional(UseTemplate),
        // isNew: z
        // templates: Templates,
        // currentTemplate: CurrentTemplate,
    })
    .partial();
export type RnvRootProjectBaseFragment = z.infer<typeof zodRootProjectBaseFragment>;

// NOTE: Need to explictly type this to generic zod object to avoid TS error:
// The inferred type of this node exceeds the maximum length the compiler will serialize...
// This is ok we only use this full schema for runtime validations. actual types
const zodRootProjectCommonSchema: AnyZodObject = z.object({ common: z.optional(zodCommonSchema) });
const zodRootProjectPlatformsSchema: AnyZodObject = z.object({ platforms: z.optional(zodPlatformsSchema) });
const zodRootProjectPluginsSchema: AnyZodObject = z.object({ plugins: z.optional(zodPluginsSchema) });
export const zodRootProjectSchema: AnyZodObject = zodRootProjectBaseFragment
    .merge(zodRootProjectCommonSchema)
    .merge(zodRootProjectPlatformsSchema)
    .merge(zodRootProjectPluginsSchema);

export type RnvRootProjectSchema = RnvRootProjectBaseFragment & {
    common?: RnvCommonSchema;
    platforms?: RnvPlatformsSchema;
    plugins?: RnvPluginsSchema;
};
